// tests/parity/graph.test.ts
//
// Diff basalted-core's link graph + hub-density output against the Python
// reference for both fixtures. Baseline JSON is generated by
// scripts/generate-graph-baseline.py.
//
// Tolerance: PRD §8.1.
//   - Note set + IDs: exact match
//   - Link list (sorted by from_id, target): exact match
//   - hub density: ε = 1e-5

import { readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { MemoryFilesystem } from "../../packages/core/src/adapters/filesystem-memory";
import { buildLinkGraph } from "../../packages/core/src/graph/builder";
import { hubPenalty } from "../../packages/core/src/graph/hub-penalty";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..", "..");

interface PyNote {
  id: number;
  rel_path: string;
  stem: string;
  word_count: number;
}

interface PyLink {
  from_id: number;
  target: string;
  target_id: number | null;
}

interface PyGraph {
  notes: PyNote[];
  links: PyLink[];
  out_link_count: Record<string, number>;
  density: Record<string, number>;
}

function loadGraphBaseline(prefix: string): PyGraph {
  const p = join(REPO_ROOT, "tests", "parity", "baseline", `graph-${prefix}.json`);
  return JSON.parse(readFileSync(p, "utf-8")) as PyGraph;
}

/** Materialise the on-disk fixture into a MemoryFilesystem rooted at the
 *  given vault dir. We use the same TS-side adapter the runtime would use,
 *  but with the bytes pre-loaded so the parity test doesn't depend on
 *  fs-node landing first (Phase 2). */
function loadFixtureIntoMemory(vault: string): { fs: MemoryFilesystem; root: string } {
  const fs = new MemoryFilesystem();
  function walk(dir: string) {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.name === ".basalt" || entry.name === ".obsidian" || entry.name === ".git") continue;
      const p = join(dir, entry.name);
      if (entry.isDirectory()) walk(p);
      else if (entry.isFile() && entry.name.endsWith(".md")) {
        const content = readFileSync(p, "utf-8");
        fs.addFile(p.replace(/\\/g, "/"), content, statSync(p).mtimeMs);
      }
    }
  }
  walk(vault);
  return { fs, root: vault.replace(/\\/g, "/") };
}

const FIXTURES = [
  { prefix: "sample-14", dir: join(REPO_ROOT, "tests", "parity", "fixtures", "sample-vault-14") },
  { prefix: "large-200", dir: join(REPO_ROOT, "tests", "parity", "fixtures", "test-vault-large") },
];

describe.each(FIXTURES)("graph parity: $prefix", ({ prefix, dir }) => {
  it("notes match by id, rel_path, stem, word_count", async () => {
    const baseline = loadGraphBaseline(prefix);
    const { fs, root } = loadFixtureIntoMemory(dir);
    const g = await buildLinkGraph(fs, root);
    expect(g.notes).toHaveLength(baseline.notes.length);
    for (const expected of baseline.notes) {
      const actual = g.notes.find((n) => n.id === expected.id);
      expect(actual, `note id ${expected.id} missing`).toBeDefined();
      if (!actual) continue;
      expect(actual.relPath).toBe(expected.rel_path);
      expect(actual.stem).toBe(expected.stem);
      expect(actual.wordCount).toBe(expected.word_count);
    }
  });

  it("links match as a sorted set (from_id, target, target_id)", async () => {
    const baseline = loadGraphBaseline(prefix);
    const { fs, root } = loadFixtureIntoMemory(dir);
    const g = await buildLinkGraph(fs, root);
    const tsKeys = g.links.map((l) => `${l.fromId}|${l.target}|${l.targetId ?? "null"}`).sort();
    const pyKeys = baseline.links
      .map((l) => `${l.from_id}|${l.target}|${l.target_id ?? "null"}`)
      .sort();
    expect(tsKeys).toEqual(pyKeys);
  });

  it("outLinkCount matches (DISTINCT target per from_id)", async () => {
    const baseline = loadGraphBaseline(prefix);
    const { fs, root } = loadFixtureIntoMemory(dir);
    const g = await buildLinkGraph(fs, root);
    for (const [idStr, expected] of Object.entries(baseline.out_link_count)) {
      const id = Number.parseInt(idStr, 10);
      expect(g.outLinkCount.get(id) ?? 0, `outLinkCount[${id}]`).toBe(expected);
    }
  });

  it("hub density within ε = 1e-5 of Python for every note", async () => {
    const baseline = loadGraphBaseline(prefix);
    const { fs, root } = loadFixtureIntoMemory(dir);
    const g = await buildLinkGraph(fs, root);
    for (const note of baseline.notes) {
      const expected = baseline.density[String(note.id)] ?? 0;
      const actual = g.density.get(note.id) ?? 0;
      expect(
        Math.abs(actual - expected),
        `density[${note.id}] ${actual} vs ${expected}`,
      ).toBeLessThanOrEqual(1e-5);
    }
  });

  it("hubPenalty(density) is in [0, 1] and non-increasing above HUB_DENSITY_SOFT", async () => {
    // Smoke check the per-note penalty across the fixture.
    const baseline = loadGraphBaseline(prefix);
    for (const expected of Object.values(baseline.density)) {
      const p = hubPenalty(expected);
      expect(p).toBeGreaterThanOrEqual(0);
      expect(p).toBeLessThanOrEqual(1);
    }
  });
});
