// tests/parity/parser.test.ts
//
// Diff basalted-core's parser output against the Python reference for every
// .md file in both fixtures. Baseline JSON is generated by
// scripts/generate-parser-baseline.py and committed under
// tests/parity/baseline/parser-{sample-14,large-200}.json.
//
// Tolerance: every field must match exactly (PRD §8.1).
// Known divergences live in docs/parsing-decisions.md; this test enforces
// that no other disagreements creep in.

import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { parseMarkdown } from "../../packages/core/src/parser/markdown";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..", "..");

interface PythonRow {
  rel_path: string;
  stem: string;
  title: string;
  created: string | null;
  updated: string | null;
  tags: string[];
  wikilinks: string[];
  word_count: number;
  content_hash: string;
}

function loadPythonBaseline(stem: string): PythonRow[] {
  const path = join(REPO_ROOT, "tests", "parity", "baseline", `parser-${stem}.json`);
  return JSON.parse(readFileSync(path, "utf-8")) as PythonRow[];
}

function walkMarkdown(vault: string): string[] {
  const out: string[] = [];
  function recurse(dir: string) {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.name === ".basalt" || entry.name === ".obsidian" || entry.name === ".git") continue;
      const p = join(dir, entry.name);
      if (entry.isDirectory()) {
        recurse(p);
      } else if (entry.isFile() && entry.name.endsWith(".md")) {
        out.push(p);
      }
    }
  }
  recurse(vault);
  return out;
}

function relPath(absolute: string, vault: string): string {
  return absolute
    .slice(vault.length + 1)
    .split("\\")
    .join("/");
}

function stemOf(file: string): string {
  const parts = file.split(/[\\/]/);
  const base = parts[parts.length - 1]!;
  return base.replace(/\.md$/, "");
}

const FIXTURES: Array<{ prefix: string; dir: string }> = [
  {
    prefix: "sample-14",
    dir: join(REPO_ROOT, "tests", "parity", "fixtures", "sample-vault-14"),
  },
  {
    prefix: "large-200",
    dir: join(REPO_ROOT, "tests", "parity", "fixtures", "test-vault-large"),
  },
];

describe.each(FIXTURES)("parser parity: $prefix", ({ prefix, dir }) => {
  if (!existsSync(dir)) {
    it.skip(`${prefix} fixture missing — skipping`, () => {});
    return;
  }

  const baseline = loadPythonBaseline(prefix);
  const byPath = new Map(baseline.map((r) => [r.rel_path, r] as const));

  const files = walkMarkdown(dir).sort();

  it("baseline + fixture have matching file counts", async () => {
    // TS may produce nulls (zero-word files filtered by walk_vault); count
    // those out before comparing.
    let nonEmpty = 0;
    for (const f of files) {
      const raw = readFileSync(f, "utf-8");
      const parsed = await parseMarkdown(raw, {
        stem: stemOf(f),
      });
      if (parsed !== null) nonEmpty++;
    }
    expect(nonEmpty).toBe(baseline.length);
  });

  for (const row of baseline) {
    it(`${row.rel_path}: matches Python parse_note`, async () => {
      const abs = join(dir, ...row.rel_path.split("/"));
      const raw = readFileSync(abs, "utf-8");
      const parsed = await parseMarkdown(raw, { stem: row.stem });
      expect(parsed).not.toBeNull();
      if (!parsed) return;

      expect(parsed.stem).toBe(row.stem);
      expect(parsed.title).toBe(row.title);
      expect(parsed.created).toBe(row.created);
      expect(parsed.updated).toBe(row.updated);
      expect(parsed.tags).toEqual(row.tags);
      expect(parsed.wikilinks).toEqual(row.wikilinks);
      expect(parsed.wordCount).toBe(row.word_count);
      expect(parsed.contentHash).toBe(row.content_hash);
    });
  }

  it("no fixture file is missing from the baseline (no silent skips)", () => {
    for (const f of files) {
      const rel = relPath(f, dir);
      if (statSync(f).size === 0) continue;
      // If the body is empty or all-whitespace, Python's walk_vault filters
      // it (word_count == 0). Skip parity for those.
      const raw = readFileSync(f, "utf-8");
      const bodyAfterFrontmatter = raw.replace(/^---[\s\S]*?\n---\s*\n?/, "");
      if (bodyAfterFrontmatter.trim().length === 0) continue;
      expect(byPath.has(rel)).toBe(true);
    }
  });
});
